### ISSUE TITLE
OSTree Base

### ISSUE THREAD

**Issue by azubieta** [nomad-desktop/nxos-iso#4]
https://github.com/nomad-desktop/ubuntu-ostree
https://ostree.readthedocs.io/en/latest/

**Comment by azubieta** [comment]
@luis-lavaire would you mind to make a brief report of the state of this issue?

**Comment by luis-lavaire** [comment]
Of course, @azubieta. Until tomorrow I will be planing the path that the project will take. ATM I choose Ubuntu as the the base distro (because we are already using it and it would make any sense to switch to Debian or another distro). The backbone of this integration will be done with shell scripts. Those will manage the bootloader configuration and trigger the updates to the filesystem when needed. Once I manage to get an stable implementation of this system, maybe I will opt to write it in Go. That will depend on the complexity of the resulting code.

**Comment by star-buck** [comment]
Just maybe a crazy idea here, but:
Since OSTree will be "read-only" and not updateable from the userpoint, how about basing it on arch?
Arch is easy to do packages and has almost always the latest since its rolling.
So it is easy to get updates of Qt+Frameworks+Plasma which will make of the Nitrux OS GUI, plus also security wise.
So almost no effort has to be put into packaging stuff by the Nitrux team, and one can easily roll out a new "OSTree" base version of Nitrux whenever one suits it without waiting for Ubuntu, which may have lost interest in anything Qt+Plasma?
Just a thought, please discuss if this makes sense or any drawbacks/advantages of Arch vs. Ubuntu.

**Comment by azubieta** [comment]
@Starbucks actually I was considering the possibilities of creating the new
system like a Linux from Scratch using the sources right from the original
developers.
Just like an Android system. This will give you full control of what and
which versions are being included in the system and there is no package
management there, so there will be no need to pack.

So I would recommend that our system image generation code should be split
in two.
One part to actually create the system in a folder.
A second to put that folder into an disk image.

Our first goal would be to replicate our existent Ubuntu based iso. If it
result easier to do arch based, so be it.

Then we can move to the lfs style.

**Comment by luis-lavaire** [comment]
@star-buck: I've been an Arch user for almost three years, until this year, because I started (again) using Ubuntu for the sake of my mates on Nitrux; because we were already using it. So it made more sense to me to use what the others guys used. Arch is very nice, but because of its rolling nature, things can get weird at any time. I'm aware that Ubuntu doesn't have the latest packages (I don't like that. Think of bugs, security breaches, etc.) and that will leave us with even more outdated packages, well a whole outdated system rather. I don't think that the Ubuntu people have any special interest on Plasma (except for their phones maybe), so I don't expect **great** advantage from using Ubuntu, at least in this point. Also, installing Plasma on Arch is pretty easy.

I think that @azubieta's idea is a really good one. That would give us very much control on what we put on the OS, the possible bugs that are on it, etc. Last year I implemented a system that behaved in this way (which I had told you already). Using a more minimal set of userspace tools (as Android does) will help us (the devs) a lot: a more manageable environment (This distro is very focused on the desktop also, not on the CLI). For example: I can be in charge of the whole userspace (I did already [here](https://github.com/nxos/busybox)). A friend of mine is working on a script that builds Plasma and KF5; that could help. So there's proof that a distro made from scratch is feasible. We could also take advantage from projects like [yocto](https://www.yoctoproject.org/), [buildroot](https://buildroot.org/) among others, because this system will share pretty much aspects with the embedded ones.

Right now I'm working on a [tool](https://github.com/luis-lavaire/mkiso) that boostraps an *buntu based system, which, by the way, I will continue using for the generation of the NXOS images. It runs on Travis-CI, so it fits well in a CI development-cycle. So we could use that until we manage to do the LFS part.

@star-buck, the idea is not that "crazy", I guess. But using Arch will definitely impose more risks (because of the rolling nature of it) than Ubuntu or a LFS. I'd really want to go more on @azubieta's way. I even have work done already in that direction.

What do you both think?

**Comment by star-buck** [comment]
I am not sure about the "from scratch" approach. I would think the
advantage of ostree is to freeze at any point and update the whole system
at once?
So the best base for that is a rolling one, because it constantly provides
fresh packages from whivh to build the ostree?

For netrunner, I actually like to go back to the base packages of
underlying debian testing as building stuff ourselves takes too much effort
that could really come from the underlying base imo?
Since the base for ostree doesnt matter to the user, since its shielded, it
only matters to the devs building it.
Maybe Suse is a good base for that matter too, either Tumbleweed or Leap?

But I dont claim any experience on this or being right, could be totally
wrong, just thinking out loud :)

**Comment by luis-lavaire** [comment]
@star-buck: yes, you can replicate the system that is running somewhere (say a server, or a machine intended just for this purpose) and deploy it on another set of machines. Updating the whole system is another advantage, because there's predictability on what you'll have (this is really good in terms of software development, testing and bug solving... too many advantages can be cited here) that's what "atomic update(s)" are.

You mention a super interesting and important point: it doesn't matter which OS do you choose to use (add to this our integration with AppImages), unless from the devs point of view. Can I suggest that we use either Arch or Ubuntu for now, and, if we manage to to make a usable system from scratch, then use that? We can actually use multiple systems once ostree is deployed on a storage unit.

**Comment by UriHerrera** [comment]
I think using Ubuntu to get familiarized with ostree would make the learning curve less steep. Once we are knowledgeable of how ostree works we can leverage Ubuntu for another base like Arch or LFS. As it has been mentioned, to the user updates of the OS will be transparent.

**Comment by star-buck** [comment]
Agreed.

**Comment by luis-lavaire** [comment]
Moved the repo to https://github.com/nomad-desktop/ubuntu-ostree. Here's where it belongs.
